version: '3'

services:
  database:
    image: mariadb:latest
    container_name: database
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    networks:
      - ce-phoenix-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "${PMA_ACCESS_PORT}:80"
    networks:
      - ce-phoenix-network
  ce-phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ce_phoenix
    env_file:
      - .env
    volumes:
      - ./data/:/var/www/html
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "${PORT}:80"
    networks:
      - ce-phoenix-network

networks:
  ce-phoenix-network:
    name: ce-phoenix-network
